[package]
name = "nnsearch-rs"
version = "0.1.0"
authors = ["mana-ysh <int.toshi13@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
ndarray = "0.15.3"
num = "0.4.0"
rand = "0.8.3"
thiserror = "1.0"