name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      run: |
        rustup toolchain install nightly
        rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Build
      run: make build
    - name: Lint
      run: make lint
    - name: Run tests
      run: make test
